version: '3.8'

services:
  # Service 1: Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Service 2: Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  # Service 3: Python Data Generator
  shop-pulse-generator:
    build:
      context: ./data_generator
    container_name: shop-pulse-generator
    depends_on:
      - kafka

  # Service 4: Apache Spark (The Processor)
  spark-processor:
    build: ./spark                  # <--- This is the fix (Simple string path)
    container_name: spark-processor
    depends_on:
      - kafka
    environment:
      - SPARK_MASTER=local[*]
    volumes:
      - ./spark_data:/opt/spark/work-dir/spark_data  # <--- NEW LINE: Maps container folder to your laptop

    command: >
      /opt/spark/bin/spark-submit 
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 
      stream_processing.py
  


  
